export const RECENT_FILES = [
  // Today – opened
  {
    id: "r1",
    name: "Brand Guidelines v3.pdf",
    size: "4.2 MB",
    lastOpened: new Date(Date.now() - 12 * 60 * 1000),
    type: "opened",
    starred: true,
    shared: true,
    kind: "pdf",
  },
  {
    id: "r2",
    name: "Q4-keynote-final.pptx",
    size: "18.6 MB",
    lastOpened: new Date(Date.now() - 45 * 60 * 1000),
    type: "opened",
    owner: "Amelia M.",
    kind: "document",
  },
  {
    id: "r3",
    name: "Hero-shot-005.png",
    size: "8.1 MB",
    lastOpened: new Date(Date.now() - 2 * 60 * 60 * 1000),
    type: "uploaded",
    uploadStatus: "complete",
    owner: "Amelia M.",
    starred: true,
    kind: "image",
  },
  {
    id: "r4",
    name: "api-routes.ts",
    size: "24 KB",
    lastOpened: new Date(Date.now() - 3 * 60 * 60 * 1000),
    type: "uploaded",
    uploadStatus: "uploading",
    uploadProgress: 72,
    owner: "Dev Team",
    kind: "code",
  },

  // Yesterday
  {
    id: "r5",
    name: "investor-deck.key",
    size: "12.4 MB",
    lastOpened: new Date(Date.now() - 26 * 60 * 60 * 1000),
    type: "opened",
    owner: "Maya P.",
    shared: true,
    kind: "document",
  },
  {
    id: "r6",
    name: "podcast-ep12.mp3",
    size: "48 MB",
    lastOpened: new Date(Date.now() - 28 * 60 * 60 * 1000),
    type: "uploaded",
    uploadStatus: "complete",
    owner: "Marketing",
    kind: "audio",
  },
  {
    id: "r7",
    name: "Design System",
    size: "248 items",
    lastOpened: new Date(Date.now() - 30 * 60 * 60 * 1000),
    type: "opened",
    owner: "Team",
    kind: "folder",
    shared: true,
  },

  // This week
  {
    id: "r8",
    name: "launch-assets",
    size: "1.2 GB",
    lastOpened: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    type: "opened",
    owner: "Design",
    kind: "folder",
  },
  {
    id: "r9",
    name: "client-archives.zip",
    size: "640 MB",
    lastOpened: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000),
    type: "uploaded",
    uploadStatus: "complete",
    owner: "Amelia M.",
    kind: "archive",
  },
  {
    id: "r10",
    name: "onboarding-video.mp4",
    size: "256 MB",
    lastOpened: new Date(Date.now() - 4.5 * 24 * 60 * 60 * 1000),
    type: "uploaded",
    uploadStatus: "failed",
    owner: "HR Team",
    kind: "video",
  },
  {
    id: "r11",
    name: "financial-report-Q3.xlsx",
    size: "2.8 MB",
    lastOpened: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000),
    type: "opened",
    owner: "Finance",
    kind: "document",
    starred: true,
  },

  // Earlier
  {
    id: "r12",
    name: "app-mockup-v2.fig",
    size: "34 MB",
    lastOpened: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    type: "opened",
    owner: "Design",
    kind: "image",
    shared: true,
  },
  {
    id: "r13",
    name: "team-photo-2026.jpg",
    size: "5.6 MB",
    lastOpened: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000),
    type: "uploaded",
    uploadStatus: "complete",
    owner: "Amelia M.",
    kind: "image",
  },
];
